name: Go

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.15', '1.16', '1.17', '1.18', '1.19', '1.20']
    name: Go ${{ matrix.go }} sample

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: go build -v .

    - name: Test-386
      run: env GOARCH=386 go test -test.run=Test_Retry_sleep -v 
      #run: env GOARCH=386 go test -v -coverprofile='coverage.out' -covermode=count ./...
      
    - name: Test-amd64
      run: env GOARCH=amd64 go test -v -coverprofile='coverage.out' -covermode=count ./...


    - name: Upload Coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.out
